rm -rf CM4/_Inc/
rm -rf Drivers/BSP/Components/_Common/
rm -rf Drivers/BSP/Components/_adv7533/
rm -rf Drivers/BSP/Components/_ampire480272/
rm -rf Drivers/BSP/Components/_ampire640480/
rm -rf Drivers/BSP/Components/_exc7200/
rm -rf Drivers/BSP/Components/_ft5336/
rm -rf Drivers/BSP/Components/_ft6x06/
rm -rf Drivers/BSP/Components/_mfxstm32l152/
rm -rf Drivers/BSP/Components/_ov9655/
rm -rf Drivers/BSP/Components/_rk043fn48h/
rm -rf Drivers/BSP/Components/_st7735/
rm -rf Drivers/BSP/Components/_stmpe811/
rm -rf Drivers/BSP/Components/_ts3510/
rm -rf Drivers/BSP/Components/_wm8994/
rm -rf Drivers/BSP/_Adafruit_Shield/
rm -rf Drivers/BSP/_STM32H743I_EVAL/
rm -rf Drivers/BSP/_STM32H745I-Discovery/
rm -rf Drivers/BSP/_STM32H747I_EVAL/
rm -rf Drivers/BSP/_STM32H750B-Discovery/
rm -rf Drivers/BSP/_STM32H7xx_Nucleo_144/
rm -rf Drivers/CMSIS/Core/_Include/
rm -rf Drivers/CMSIS/Core_A/_Include/
rm -rf Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/JTest/_inc/
rm -rf Drivers/CMSIS/DSP/DSP_Lib_TestSuite/Common/_inc/
rm -rf Drivers/CMSIS/DSP/DSP_Lib_TestSuite/RefLibs/_inc/
rm -rf Drivers/CMSIS/DSP/Examples/ARM/_arm_convolution_example/
rm -rf Drivers/CMSIS/DSP/Examples/ARM/_arm_fir_example/
rm -rf Drivers/CMSIS/DSP/Examples/ARM/_arm_graphic_equalizer_example/
rm -rf Drivers/CMSIS/DSP/Examples/ARM/_arm_linear_interp_example/
rm -rf Drivers/CMSIS/DSP/Examples/ARM/_arm_matrix_example/
rm -rf Drivers/CMSIS/DSP/Examples/ARM/_arm_signal_converge_example/
rm -rf Drivers/CMSIS/DSP/_Include/
rm -rf Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/_cifar10/
rm -rf Drivers/CMSIS/NN/Examples/ARM/arm_nn_examples/_gru/
rm -rf Drivers/CMSIS/NN/NN_Lib_Tests/_nn_test/
rm -rf Drivers/CMSIS/NN/_Include/
rm -rf Drivers/CMSIS/RTOS/_Template/
rm -rf Drivers/CMSIS/RTOS2/_Include/
rm -rf Drivers/CMSIS/RTOS2/_Template/
rm -rf Middlewares/ST/STM32_USB_Device_Library/Class/AUDIO/_Inc/
rm -rf Middlewares/ST/STM32_USB_Device_Library/Class/CDC/_Inc/
rm -rf Middlewares/ST/STM32_USB_Device_Library/Class/CustomHID/_Inc/
rm -rf Middlewares/ST/STM32_USB_Device_Library/Class/DFU/_Inc/
rm -rf Middlewares/ST/STM32_USB_Device_Library/Class/HID/_Inc/
rm -rf Middlewares/ST/STM32_USB_Device_Library/Class/MSC/_Inc/
rm -rf Middlewares/ST/STM32_USB_Device_Library/Class/Template/_Inc/
rm -rf Middlewares/ST/STM32_USB_Device_Library/Core/_Inc/
rm -rf Middlewares/ST/STM32_USB_Host_Library/Class/AUDIO/_Inc/
rm -rf Middlewares/ST/STM32_USB_Host_Library/Class/CDC/_Inc/
rm -rf Middlewares/ST/STM32_USB_Host_Library/Class/HID/_Inc/
rm -rf Middlewares/ST/STM32_USB_Host_Library/Class/MSC/_Inc/
rm -rf Middlewares/ST/STM32_USB_Host_Library/Class/MTP/_Inc/
rm -rf Middlewares/ST/STM32_USB_Host_Library/Class/Template/_Inc/
rm -rf Middlewares/ST/STM32_USB_Host_Library/Core/_Inc/
rm -rf Middlewares/Third_Party/FatFs/_src/
rm -rf Middlewares/Third_Party/LibJPEG/_include/
rm -rf Middlewares/Third_Party/LwIP/doc/_doxygen/
rm -rf Middlewares/Third_Party/LwIP/src/apps/_snmp/
rm -rf Middlewares/Third_Party/LwIP/test/_fuzz/
rm -rf Middlewares/Third_Party/LwIP/test/_unit/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/_test/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/examples/system/freertos/zynqmp_r5/_zynqmp_amp_demo/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/examples/system/generic/zynqmp_r5/_zynqmp_amp_demo/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/examples/system/linux/zynqmp/_zynqmp_amp_demo/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/lib/compiler/_gcc/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/lib/compiler/_iar/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/lib/include/metal/compiler/_gcc/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/lib/include/metal/compiler/_iar/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/lib/include/metal/compiler/_mdk-arm/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/lib/include/metal/processor/_arm/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/lib/include/metal/system/_generic/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/lib/processor/_aarch64/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/lib/processor/_arm/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/lib/processor/_microblaze/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/lib/processor/_x86_64/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/lib/system/_freertos/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/lib/system/_generic/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/lib/system/_linux/
rm -rf Middlewares/Third_Party/OpenAMP/libmetal/lib/system/_zephyr/
rm -rf Middlewares/Third_Party/OpenAMP/mw_if/_app_if/
rm -rf Middlewares/Third_Party/OpenAMP/mw_if/_platform_if/
rm -rf Middlewares/Third_Party/OpenAMP/open-amp/apps/examples/_echo/
rm -rf Middlewares/Third_Party/OpenAMP/open-amp/apps/examples/_matrix_multiply/
rm -rf Middlewares/Third_Party/OpenAMP/open-amp/apps/examples/_rpc_demo/
rm -rf Middlewares/Third_Party/OpenAMP/open-amp/apps/machine/_zynq7/
rm -rf Middlewares/Third_Party/OpenAMP/open-amp/apps/machine/_zynqmp/
rm -rf Middlewares/Third_Party/OpenAMP/open-amp/apps/machine/_zynqmp_r5/
rm -rf Middlewares/Third_Party/OpenAMP/open-amp/apps/system/linux/machine/_generic/
rm -rf Middlewares/Third_Party/OpenAMP/open-amp/apps/tests/_msg/
rm -rf Middlewares/Third_Party/OpenAMP/open-amp/lib/_rpmsg/
rm -rf Middlewares/Third_Party/OpenAMP/open-amp/lib/include/_openamp/
rm -rf Middlewares/Third_Party/mbedTLS/_configs/
rm -rf Middlewares/Third_Party/mbedTLS/doxygen/_input/
rm -rf Middlewares/Third_Party/mbedTLS/include/_mbedtls/
rm -rf Middlewares/Third_Party/mbedTLS/library/_templates/

